ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb.daws-90s.sbs
REDIS_HOST: redis.daws-90s.sbs
CATALOGUE_HOST: catalogue.daws-90s.sbs
MYSQL_HOST: mysql.daws-90s.sbs
CART_HOST: cart.daws-90s.sbs
RABBITMQ_HOST: rabbitmq.daws-90s.sbs
USER_HOST: user.daws-90s.sbs
PAYMENT_HOST: payment.daws-90s.sbs
SHIPPING_HOST: shipping.daws-90s.sbs
#FRONTEND_HOST: frontend.daws-90s.sbs