[local]
localhost

[mongodb]
mongodb.daws-90s.sbs

[redis]
redis.daws-90s.sbs

[mysql]
mysql.daws-90s.sbs

[rabbitmq]
rabbitmq.daws-90s.sbs

[catalogue]
catalogue.daws-90s.sbs

[user]
user.daws-90s.sbs

[cart]
cart.daws-90s.sbs

[shipping]
shipping.daws-90s.sbs

[payment]
payment.daws-90s.sbs

[frontend]
frontend.daws-90s.sbs