- name: get the password from AWS secret manager
  debug:
    msg: "{{ lookup('amazon.aws.aws_secret', 'roboshop/msql_root_pssword', region='us-east-1') | from_json }}"
- name: print password
  debug:
     msg: "{{ root_password.msql_root_pssword }}"
- name: install mysql server
  package:
    name: mysql-server
    state: present
- name: start and enable mysql
  service:
    state: started
    enabled: yes
    name: mysqld
- name: setup root ansible_password
  #command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"
  command: mysql_secure_installation --set-root-pass "{{ root_password.msql_root_pssword }}"